name: Deploy Infrastructure

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  terraform-check:
    name: Terraform check
    runs-on: ubuntu-latest
    steps:
      - name: Terraform format checking
        run: terraform fmt

  terraform-plan:
    name: Terraform planning
    runs-on: ubuntu-latest
    needs: terraform-check
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ROLE_ARN }}:role/GithubActionsRole
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        run: terraform init
      - name: Terraform planning
        run: terraform plan

  terraform-apply:
    name: Terraform deploying
    runs-on: ubuntu-latest
    needs: terraform-plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ROLE_ARN }}:role/GithubActionsRole
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        run: terraform init
      - name: Terraform deploying
        run: terraform apply